version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptosocial
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend/nest
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cryptosocial?schema=public
      JWT_SECRET: your-super-secret-key-change-in-production
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data: 