version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email modima@morevis.ru --agree-tos --no-eff-email -d morevis.ru -d www.morevis.ru

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  backend:
    build: 
      context: ./backend/nest
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: https://morevis.ru/api
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 